# Stefan Achatz 2012
#
# Tries to find libgdk_pixbuf-2.0 and sets following variables according to found capabilities:
#
# LIBEVENT_FOUND
# LIBEVENT_INCLUDE_DIRS
# LIBEVENT_LIBRARIES

FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(LIBEVENT libevent)

FIND_PATH(LIBEVENT_INCLUDE_DIRS event.h
	HINTS
	${PKG_LIBEVENT_INCLUDE_DIRS}
	${PKG_LIBEVENT_INCLUDEDIR}
	#PATH_SUFFIXES gtk-2.0
)

FIND_LIBRARY(LIBEVENT_LIBRARIES event
	HINTS ${PKG_LIBEVENT_LIBRARY_DIRS}
)

IF(LIBEVENT_LIBRARIES AND LIBEVENT_INCLUDE_DIRS)
	SET(LIBEVENT_FOUND true)
ENDIF()

IF(LIBEVENT_FIND_REQUIRED AND NOT LIBEVENT_FOUND)
	MESSAGE(FATAL_ERROR "Could not find LIBEVENT")
ENDIF()
