# Configuration file for job scratch

[window-names]
include="foo*", "bar", "baz" # Regular expressions that are used to match the window title
exclude="foo", "bar", "baz"

[workspace-names]
include="füüüü", "bar", "baz"
exclude="foo", "flönk", "áßßßßß"

[timefile]
filename=/path/to/file
granularity=1h

[actions]
# TODO






#{
#	"granularity" : 10,
#	"window_names" :[ "home/mox/scratch", "~/scratch", "okular" ],
#	"workspace_names" :[ "" ]
#}
