# Try to find syslog.h for Syslog


IF (GDK-PIXBUF_INCLUDE_DIRS)
	# Already in cache, be silent
	SET(GDK-PIXBUF_FIND_QUIETLY TRUE)
ENDIF (GDK-PIXBUF_INCLUDE_DIRS)

FIND_PATH(GDK-PIXBUF_INCLUDE_DIRS NAMES gdk-pixbuf/gdk-pixbuf.h HINTS /usr/include/gdk-pixbuf-2.0)
#FIND_PATH(GDK-PIXBUF_INCLUDE_DIR2 NAMES glibconfig.h HINTS  /usr/lib/glib-2.0/include)

FIND_LIBRARY(GDK-PIXBUF_LIBRARIES gdk_pixbuf-2.0
	PATHS /usr/lib
	HINTS ${PKG_GDK-PIXBUF_LIBDIR}
)


IF(GDK-PIXBUF_INCLUDE_DIRS AND GDK-PIXBUF_LIBRARIES) 
	SET(GDK-PIXBUF_FOUND TRUE) 
	#SET(GDK-PIXBUF_INCLUDE_DIRS ${GDK-PIXBUF_INCLUDE_DIR1} ${GDK-PIXBUF_INCLUDE_DIR2})
ENDIF(GDK-PIXBUF_INCLUDE_DIRS AND GDK-PIXBUF_LIBRARIES) 
	#ENDIF(GDK-PIXBUF_INCLUDE_DIR1 AND GDK-PIXBUF_INCLUDE_DIR2 AND GDK-PIXBUF_LIBRARIES) 

IF(GDK-PIXBUF_FOUND) 
	set(CMAKE_REQUIRED_INCLUDES ${GLIB-2.0_INCLUDE_DIRS})
	set(CMAKE_REQUIRED_INCLUDES)
	IF(NOT GDK-PIXBUF_FIND_QUIETLY) 
		MESSAGE(STATUS "Found GDK-PIXBUF headers: ${GDK-PIXBUF_INCLUDE_DIRS}/glib-2.0/glib.h") 
	ENDIF(NOT GDK-PIXBUF_FIND_QUIETLY) 
ELSE(GDK-PIXBUF_FOUND) 
	IF(Syslog_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find glib") 
	ENDIF(Syslog_FIND_REQUIRED) 
ENDIF(GDK-PIXBUF_FOUND) 

MARK_AS_ADVANCED(
	GDK-PIXBUF_FOUND
	GDK-PIXBUF_INCLUDE_DIRS
	GDK-PIXBUF_LIBRARIES
	)

