# Try to find syslog.h for Syslog


IF (CONFUSE_INCLUDE_DIRS)
	# Already in cache, be silent
	SET(CONFUSE_FIND_QUIETLY TRUE)
ENDIF (CONFUSE_INCLUDE_DIRS)

#FIND_PATH(CONFUSE_INCLUDE_DIRS NAMES gdk-pixbuf/gdk-pixbuf.h HINTS /usr/include/gdk-pixbuf-2.0)

FIND_LIBRARY(CONFUSE_LIBRARIES confuse
	PATHS /usr/lib
	HINTS ${PKG_CONFUSE_LIBDIR}
)


IF(CONFUSE_LIBRARIES) 
	SET(CONFUSE_FOUND TRUE) 
ENDIF(CONFUSE_LIBRARIES) 

IF(CONFUSE_FOUND) 
	set(CMAKE_REQUIRED_INCLUDES ${GLIB-2.0_INCLUDE_DIRS})
	set(CMAKE_REQUIRED_INCLUDES)
	IF(NOT CONFUSE_FIND_QUIETLY) 
		MESSAGE(STATUS "Found CONFUSE headers: ${CONFUSE_INCLUDE_DIRS}/glib-2.0/glib.h") 
	ENDIF(NOT CONFUSE_FIND_QUIETLY) 
ELSE(CONFUSE_FOUND) 
	IF(Syslog_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find glib") 
	ENDIF(Syslog_FIND_REQUIRED) 
ENDIF(CONFUSE_FOUND) 

MARK_AS_ADVANCED(
	CONFUSE_FOUND
	#CONFUSE_INCLUDE_DIRS
	CONFUSE_LIBRARIES
	)

