# Try to find  Libuv


IF (LIBUV_INCLUDE_DIRS)
	# Already in cache, be silent
	SET(LIBUV_FIND_QUIETLY TRUE)
ENDIF (LIBUV_INCLUDE_DIRS)

FIND_LIBRARY(LIBUV_LIBRARIES NAMES uv)
FIND_PATH(LIBUV_INCLUDE_DIRS uv.h
	PATH_SUFFIXES include/uv include
	)

IF(LIBUV_INCLUDE_DIRS)
	SET(LIBUV_FOUND TRUE)
ENDIF(LIBUV_INCLUDE_DIRS)

IF(LIBUV_FOUND)
	set(CMAKE_REQUIRED_INCLUDES ${LIBUV_INCLUDE_DIRS})
	set(CMAKE_REQUIRED_INCLUDES)
	IF(NOT LIBUV_FIND_QUIETLY)
		MESSAGE(STATUS "Found Libuv headers: ${LIBUV_INCLUDE_DIRS}/uv.h")
		MESSAGE(STATUS "Found Libuv lib: ${LIBUV_LIBRARIES}")
	ENDIF(NOT LIBUV_FIND_QUIETLY)
ELSE(LIBUV_FOUND)
	IF(LIBUV_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find Libuv")
	ENDIF(LIBUV_FIND_REQUIRED)
ENDIF(LIBUV_FOUND)

MARK_AS_ADVANCED(
	LIBUV_INCLUDE_DIRS
	LIBUV_LIBRARIES
	LIBUV_SECOND_ARGUMENT_IS_CONST
	)
