#
#
# Tries to find libjsoncpp and sets following variables according to found capabilities:
#
# LIBJSONCPP_FOUND
# LIBJSONCPP_INCLUDE_DIRS
# LIBJSONCPP_LIBRARIES

FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PKG_LIBJSONCPP libjsoncpp)

FIND_PATH(LIBJSONCPP_LIBJSONCPP_INCLUDE_DIRS json/features.h
	HINTS
	${PKG_LIBJSONCPP_INCLUDE_DIRS}
	${PKG_LIBJSONCPP_INCLUDEDIR}
	PATH_SUFFIXES jsoncpp
)

message("					LIBJSONCPP_LIBJSONCPP_INCLUDE_DIRS: " ${LIBJSONCPP_LIBJSONCPP_INCLUDE_DIRS})


FIND_LIBRARY(LIBJSONCPP_LIBJSONCPP_LIBRARIES jsoncpp
	PATHS ${FOO_PREFIX}/lib /usr/lib
	HINTS
	${PKG_LIBJSONCPP_LIBDIR}
)
message("					LIBJSONCPP_LIBJSONCPP_LIBRARIES: " ${LIBJSONCPP_LIBJSONCPP_LIBRARIES})

IF(LIBJSONCPP_LIBJSONCPP_LIBRARIES AND LIBJSONCPP_LIBJSONCPP_INCLUDE_DIRS)
	SET(LIBJSONCPP_FOUND true)
ENDIF()

IF(LIBJSONCPP_FIND_REQUIRED AND NOT LIBJSONCPP_FOUND)
	MESSAGE(FATAL_ERROR "Could not find libjsoncpp")
ENDIF()

SET(LIBJSONCPP_INCLUDE_DIRS ${LIBJSONCPP_LIBJSONCPP_INCLUDE_DIRS})
SET(LIBJSONCPP_LIBRARIES ${LIBJSONCPP_LIBJSONCPP_LIBRARIES}})

MARK_AS_ADVANCED(
	LIBJSONCPP_INCLUDE_DIRS
	LIBJSONCPP_LIBRARIES
	LIBJSONCPP_FOUND
)
