# Try to find syslog.h for Syslog




FIND_LIBRARY(GOBJECT_LIBRARIES gobject-2.0
	PATHS /usr/lib
	HINTS ${PKG_GOBJECT_LIBDIR}
)


IF(GOBJECT_LIBRARIES) 
	SET(GOBJECT_FOUND TRUE) 
ENDIF(GOBJECT_LIBRARIES) 
#ENDIF(GOBJECT_INCLUDE_DIR1 AND GOBJECT_INCLUDE_DIR2 AND GOBJECT_LIBRARIES) 

IF(GOBJECT_FOUND) 
	set(CMAKE_REQUIRED_INCLUDES ${GOBJECT-2.0_INCLUDE_DIRS})
	set(CMAKE_REQUIRED_INCLUDES)
	IF(NOT GOBJECT_FIND_QUIETLY) 
		MESSAGE(STATUS "Found GOBJECT headers: ${GOBJECT_INCLUDE_DIRS}/glib-2.0/glib.h") 
	ENDIF(NOT GOBJECT_FIND_QUIETLY) 
ELSE(GOBJECT_FOUND) 
	IF(Syslog_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find glib") 
	ENDIF(Syslog_FIND_REQUIRED) 
ENDIF(GOBJECT_FOUND) 

MARK_AS_ADVANCED(
	GOBJECT_FOUND
	GOBJECT_LIBRARIES
	)

